# Generated by Django 4.1.4 on 2023-01-07 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_info',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_corp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_number', models.CharField(blank=True, max_length=100, null=True)),
                ('client_address', models.CharField(blank=True, max_length=100, null=True)),
                ('client_type', models.CharField(blank=True, max_length=100, null=True)),
                ('client_job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('client_email', models.CharField(blank=True, max_length=100, null=True)),
                ('client_sub_email', models.CharField(blank=True, max_length=100, null=True)),
                ('client_tel', models.CharField(blank=True, max_length=100, null=True)),
                ('client_sub_tel', models.CharField(blank=True, max_length=100, null=True)),
                ('client_fax', models.CharField(blank=True, max_length=100, null=True)),
                ('etc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
