# Generated by Django 4.1.4 on 2023-01-09 22:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sale_info',
            fields=[
                ('sale_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_id', models.ForeignKey(blank=True, db_column='client_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.client_info')),
            ],
        ),
        migrations.CreateModel(
            name='item_info',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('item_type', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.client_info')),
            ],
        ),
        migrations.CreateModel(
            name='buy_info',
            fields=[
                ('buy_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('buy_date', models.DateField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('vat_check', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('total_money', models.IntegerField(blank=True, null=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('pay_check', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('client_id', models.ForeignKey(blank=True, db_column='client_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.client_info')),
                ('item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.item_info')),
            ],
        ),
    ]
