# Generated by Django 4.1.4 on 2023-01-22 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sale_info_item_info_buy_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_info',
            fields=[
                ('car_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('car_name', models.CharField(blank=True, max_length=100, null=True)),
                ('car_type', models.CharField(blank=True, max_length=100, null=True)),
                ('car_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
